### ISSUE TITLE
Sitecore 9 Compatability

### ISSUE THREAD

**Issue by rdonnelly02** [thecadams/301RedirectModule#40]
Hello,

Is this module compatible in Sitecore 9?  I tried to install the module and upon changing the RedirectModule.Config values for the settings (below) to true 

   <setting name="SharedSource.RedirectModule.RedirectionType.Pattern" value="true"/>
   <setting name="SharedSource.RedirectModule.RedirectionType.Rules" value="true"/>

 I am getting an exception:

Exception information: 
    Exception type: MissingMethodException 
    Exception message: Method not found: 'Sitecore.Links.LinkProvider Sitecore.Links.LinkManager.get_Provider()'.
   at SharedSource.RedirectModule.Processors.RedirectProcessor.CheckForRegExMatch(Database db, String requestedUrl, String requestedPathAndQuery, HttpRequestArgs args)
   at SharedSource.RedirectModule.Processors.RedirectProcessor.Process(HttpRequestArgs args)
   at (Object , Object[] )
   at Sitecore.Pipelines.CorePipeline.Run(PipelineArgs args)
   at Sitecore.Pipelines.DefaultCorePipelineManager.Run(String pipelineName, PipelineArgs args, String pipelineDomain)
   at Sitecore.Web.RequestEventsHandler.OnPostAuthenticateRequest(HttpContextBase context)
   at Sitecore.Nexus.Web.HttpModule.(Object , EventArgs )
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Is there something else that I need to configure?

**Comment by thecadams** [comment]
Nope, that looks like they removed a method in Sitecore 9 and it seems it'll require some code changes to fix.

**Comment by rdonnelly02** [comment]
That's what I was afraid of...

Few additional questions:

-Is this something that you plan on working on by any chance, or should we go about developing internally?

-Do you know of any workarounds that we could potentially try?

-Do you have any recommendations of tools/modules that might work in SC9?

Thanks so much for your response!

**Comment by thecadams** [comment]
Sorry but I'm not going to be able to help out validating this. It took me many months to convince Sitecore to give me a trial license, and then I find out that you have to write code to get the damn thing to install - even just with reasonable defaults!? If I was a well-paid consultant I'd be very happy with this state of affairs, but I'm not. Anyway so I tried a bunch of times to get a working Sitecore 9 installation and got tripped up by a never ending series of troubles getting windows, visual studio, solr, SQL Server, and Sitecore install framework to talk to each other. Microsoft's VMs they package have a 30-day expiry on Visual Studio and a 90-day expiry on WIndows, and Sitecore only gives a 60-day license, so everything is just going to expire on me even if I snapshot the VM. Unfortunately Visual Studio has already expired on every VM I can download from Microsoft, and for some reason the expired license for the version of Visual Studio they package prevents me using VS community edition, it just shuts down after a few minutes. For me to be willing to spend the time, I need to see Microsoft get serious about free-to-use software instead of crippling their stuff with trials, I'll need to see Sitecore take an interest in the "default everything except X and Y" use case that I as an open-source maintainer care about. In the meantime though I am going to cease working on this module.

I will, however, merge a PR if it is code-reviewed by someone from another GitHub organization.

**Comment by rdonnelly02** [comment]
Man! Okay, no worries at all. If that’s he route the team goes down, I’ll definitely let you know. Thanks again for getting back to me.

**Comment by thecadams** [comment]
No worries! If you wanted to get a PR merged though I’m more than happy to - just need that review :)

**Comment by bkschmitz** [comment]
We have a need for this module (were using it in 8.2 update 2 then upgraded to 9 initial) We have someone looking through the code. Would you be willing to package a Sitecore 9 version once we submit a pull request?

**Comment by kaalen** [comment]
There's now also a pull request for upgrade to Sitecore 9.1

**Comment by estockwell-alpert** [comment]
Is there a release with the Sitecore 9 changes?

**Comment by thecadams** [comment]
Sure! The latest release should be Sitecore 9 compatible.
